export const LINE_COLORS = {
    orange: '#ed8b00',
    red: '#da291c',
    green: '#00843d',
    blue: '#003da5'
};

export const TRAINS = {
    red: [
        { label: "Ashmont/Braintree", value: "ashmontbraintree", selectedBackgroundColor: "#7e3af2" },
        { label: "Alewife", value: "alewife", selectedBackgroundColor: "#7e3af2", reverseOptions: true }
    ],
    blue: [
        { label: "Bowdoin", value: "bowdoin", selectedBackgroundColor: "#7e3af2" },
        { label: "Wonderland", value: "wonderland", selectedBackgroundColor: "#7e3af2", reverseOptions: true }
    ],
    orange: [
        { label: "Forest Hills", value: "foresthills", selectedBackgroundColor: "#7e3af2" },
        { label: "Oak Grove", value: "oakgrove", selectedBackgroundColor: "#7e3af2", reverseOptions: true }            
    ],
    greenb: [
        { label: "Boston College", value: "bostoncollege", selectedBackgroundColor: "#7e3af2" },
        { label: "Government Center", value: "governmentcenterb", selectedBackgroundColor: "#7e3af2", reverseOptions: true }
    ],
    greenc: [
        { label: "Cleveland Circle", value: "clevelandcircle", selectedBackgroundColor: "#7e3af2" },
        { label: "Government Center", value: "governmentcenterc", selectedBackgroundColor: "#7e3af2", reverseOptions: true }
    ],
    greend: [
        { label: "Riverside", value: "riverside", selectedBackgroundColor: "#7e3af2" },
        { label: "Union Square", value: "Union Square", selectedBackgroundColor: "#7e3af2", reverseOptions: true }
    ],
    greene: [
        { label: "Heath Street", value: "heathstreet", selectedBackgroundColor: "#7e3af2" },
        { label: "Medford/Tufts", value: "medfordtufts", selectedBackgroundColor: "#7e3af2", reverseOptions: true }
    ],
};

export const LINES = [
    { value: 'red', label: 'Red Line', color: '#da291c' },
    { value: 'blue', label: 'Blue Line', color: '#003da5' },
    { value: 'orange', label: 'Orange Line', color: '#d67d00' },
    { value: 'greenb', label: 'Green Line B', color: '#00843d' },
    { value: 'greenc', label: 'Green Line C', color: '#00843d' },
    { value: 'greend', label: 'Green Line D', color: '#00843d' },
    { value: 'greene', label: 'Green Line E', color: '#00843d' },
];

export const STATIONS = {
    red: [
        { value: 'alewife', label: 'Alewife' },
        { value: 'davis', label: 'Davis' },
        { value: 'porter', label: 'Porter' },
        { value: 'harvard', label: 'Harvard' },
        { value: 'central', label: 'Central' },
        { value: 'kendallmit', label: 'Kendall/MIT' },
        { value: 'charlesmgh', label: 'Charles/MGH' },
        { value: 'parkstreet', label: 'Park Street' },
        { value: 'downtowncrossing', label: 'Downtown Crossing' },
        { value: 'southstation', label: 'South Station' },
        { value: 'broadway', label: 'Broadway' },
        { value: 'andrew', label: 'Andrew' },
        { value: 'jfkumassbraintree', label: 'JFK/UMass (Braintree)' },
        { value: 'northquincy', label: 'North Quincy' },
        { value: 'wollaston', label: 'Wollaston' },
        { value: 'quincycenter', label: 'Quincy Center' },
        { value: 'quincyadams', label: 'Quincy Adams' },
        { value: 'braintree', label: 'Braintree' },
    ],
    blue: [
        { value: 'wonderland', label: 'Wonderland' },
        { value: 'reverebeach', label: 'Revere Beach' },
        { value: 'beachmont', label: 'Beachmont' },
        { value: 'suffolkdowns', label: 'Suffolk Downs' },
        { value: 'orientheights', label: 'Orient Heights' },
        { value: 'woodisland', label: 'Wood Island' },
        { value: 'airport', label: 'Airport' },
        { value: 'maverick', label: 'Maverick' },
        { value: 'aquarium', label: 'Aquarium' },
        { value: 'state', label: 'State' },
        { value: 'governmentcenter', label: 'Government Center' },
        { value: 'bowdoin', label: 'Bowdoin' },
    ],
    orange: [
        { value: 'oakgrove', label: 'Oak Grove' },
        { value: 'maldencenter', label: 'Malden Center' },
        { value: 'wellington', label: 'Wellington' },
        { value: 'assembly', label: 'Assembly' },
        { value: 'sullivan square', label: 'Sullivan Square' },
        { value: 'communitycollege', label: 'Community College' },
        { value: 'northstation', label: 'North Station' },
        { value: 'haymarket', label: 'Haymarket' },
        { value: 'state', label: 'State' },
        { value: 'downtowncrossing', label: 'Downtown Crossing' },
        { value: 'chinatown', label: 'Chinatown' },
        { value: 'tuftsmedicalcenter', label: 'Tufts Medical Center' },
        { value: 'backbay', label: 'Back Bay' },
        { value: 'massachusettsavenue', label: 'Massachusetts Avenue' },
        { value: 'ruggles', label: 'Ruggles' },
        { value: 'roxburycrossing', label: 'Roxbury Crossing' },
        { value: 'jacksonsquare', label: 'Jackson Square' },
        { value: 'stonybrook', label: 'Stony Brook' },
        { value: 'greenstreet', label: 'Green Street' },
        { value: 'foresthills', label: 'Forest Hills' },
    ],
    greenb: [
        { value: 'governmentcenter', label: 'Government Center' },
        { value: 'parkstreet', label: 'Park Street' },
        { value: 'boylston', label: 'Boylston' },
        { value: 'arlington', label: 'Arlington' },
        { value: 'copley', label: 'Copley' },
        { value: 'hynesconventioncenter', label: 'Hynes Convention Center' },
        { value: 'kenmore', label: 'Kenmore' },
        { value: 'blandfordstreet', label: 'Blandford Street' },
        { value: 'bostonuniversityeast', label: 'Boston University East' },
        { value: 'bostonuniversitycentral', label: 'Boston University Central' },
        { value: 'babcockstreet', label: 'Babcock Street' },
        { value: 'packardscorner', label: 'Packard\'s Corner' },
        { value: 'harvardavenue', label: 'Harvard Avenue' },
        { value: 'griggsstreet', label: 'Griggs Street' },
        { value: 'allstonstreet', label: 'Allston Street' },
        { value: 'warrenstreet', label: 'Warren Street' },
        { value: 'washingtonstreet', label: 'Washington Street' },
        { value: 'sutherlandroad', label: 'Sutherland Road' },
        { value: 'chiswickroad', label: 'Chiswick Road' },
        { value: 'chestnuthillavenue', label: 'Chestnut Hill Avenue' },
        { value: 'southstreet', label: 'South Street' },
        { value: 'bostoncollege', label: 'Boston College' },
    ],
    greenc: [
        { value: 'governmentcenter', label: 'Government Center' },
        { value: 'parkstreet', label: 'Park Street' },
        { value: 'boylston', label: 'Boylston' },
        { value: 'arlington', label: 'Arlington' },
        { value: 'copley', label: 'Copley' },
        { value: 'hynesconventioncenter', label: 'Hynes Convention Center' },
        { value: 'kenmore', label: 'Kenmore' },
        { value: 'saintmarysstreet', label: 'Saint Mary\'s Street' },
        { value: 'hawesstreet', label: 'Hawes Street' },
        { value: 'kentstreet', label: 'Kent Street' },
        { value: 'saintpaulstreet', label: 'Saint Paul Street' },
        { value: 'coolidgecorner', label: 'Coolidge Corner' },
        { value: 'summitavenue', label: 'Summit Avenue' },
        { value: 'brandonhall', label: 'Brandon Hall' },
        { value: 'fairbanksstreet', label: 'Fairbanks Street' },
        { value: 'washingtonsquare', label: 'Washington Square' },
        { value: 'tappanstreet', label: 'Tappan Street' },
        { value: 'deanroad', label: 'Dean Road' },
        { value: 'englewoodavenue', label: 'Englewood Avenue' },
        { value: 'clevelandcircle', label: 'Cleveland Circle' },
    ],
    greend: [
        { value: 'unionsquare', label: 'Union Square' },
        { value: 'lechmere', label: 'Lechmere' },
        { value: 'scienceparkwestend', label: 'Science Park/West End' },
        { value: 'northstation', label: 'North Station' },
        { value: 'haymarket', label: 'Haymarket' },
        { value: 'governmentcenter', label: 'Government Center' },
        { value: 'parkstreet', label: 'Park Street' },
        { value: 'boylston', label: 'Boylston' },
        { value: 'arlington', label: 'Arlington' },
        { value: 'copley', label: 'Copley' },
        { value: 'hynesconventioncenter', label: 'Hynes Convention Center' },
        { value: 'kenmore', label: 'Kenmore' },
        { value: 'fenway', label: 'Fenway' },
        { value: 'longwood', label: 'Longwood' },
        { value: 'brooklinevillage', label: 'Brookline Village' },
        { value: 'brooklinehills', label: 'Brookline Hills' },
        { value: 'beaconsfield', label: 'Beaconsfield' },
        { value: 'reservoir', label: 'Reservoir' },
        { value: 'chestnuthill', label: 'Chestnut Hill' },
        { value: 'newtoncentre', label: 'Newton Centre' },
        { value: 'newtonhighlands', label: 'Newton Highlands' },
        { value: 'eliot', label: 'Eliot' },
        { value: 'waban', label: 'Waban' },
        { value: 'woodland', label: 'Woodland' },
        { value: 'riverside', label: 'Riverside' },
    ],
    greene: [
        { value: 'medfordtufts', label: 'Medford/Tufts' },
        { value: 'ballsquare', label: 'Ball Square' },
        { value: 'magounsquare', label: 'Magoun Square' },
        { value: 'gilmansquare', label: 'Gilman Square' },
        { value: 'eastsomerville', label: 'East Somerville' },
        { value: 'lechmere', label: 'Lechmere' },
        { value: 'science Park/West End', label: 'Science Park/West End' },
        { value: 'north Station', label: 'North Station' },
        { value: 'haymarket', label: 'Haymarket' },
        { value: 'government Center', label: 'Government Center' },
        { value: 'park Street', label: 'Park Street' },
        { value: 'boylston', label: 'Boylston' },
        { value: 'arlington', label: 'Arlington' },
        { value: 'copley', label: 'Copley' },
        { value: 'prudential', label: 'Prudential' },
        { value: 'symphony', label: 'Symphony' },
        { value: 'northeasternuniversity', label: 'Northeastern University' },
        { value: 'museumoffinearts', label: 'Museum of Fine Arts' },
        { value: 'longwoodmedicalarea', label: 'Longwood Medical Area' },
        { value: 'brighamcircle', label: 'Brigham Circle' },
        { value: 'fenwoodroad', label: 'Fenwood Road' },
        { value: 'missionpark', label: 'Mission Park' },
        { value: 'riverway', label: 'Riverway' },
        { value: 'backofthehill', label: 'Back of the Hill' },
        { value: 'heathstreet', label: 'Heath Street' },
    ]

};